// Package fixtures generates the deterministic synthetic PMTiles corpus and
// its manifest. Output depends only on this package's source.
package fixtures

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/lansenou/pmtiles-conformance-lab/internal/pmtiles"
)

// Version is the generator version recorded in the manifest. Bump it whenever
// generated bytes change.
const Version = "0.2.0"

// Spec pin (docs/plan.md §2).
var specRef = SpecRef{
	Repository: "https://github.com/protomaps/PMTiles",
	Path:       "spec/v3/spec.md",
	Revision:   "8b8ddea4dbff1b0104cf2bebf2f7ff35c91b41d5",
	Version:    "3.6",
}

// ManifestSchema identifies the manifest format.
const ManifestSchema = "pmtiles-lab-manifest/1"

// File is one generated file.
type File struct {
	Path  string // slash-separated, relative to the output directory
	Bytes []byte
}

// rootTiles is the tile set shared by the root-only fixtures: contiguous
// offsets (0,1,2), a deduplicated tile (id 4 reuses id 0's bytes: a backward,
// noncontiguous offset), a run of three (ids 5-7), a z2 tile and absences.
var rootTiles = []tile{
	{0, 0, 0, "red"},
	{1, 0, 0, "green"},
	{1, 0, 1, "blue"},
	{1, 1, 0, "red"},                                        // id 4, dedup of id 0
	{2, 0, 0, "gray"}, {2, 1, 0, "gray"}, {2, 1, 1, "gray"}, // ids 5, 6, 7: one run
	{2, 3, 0, "yellow"}, // id 20
}

var rootAbsent = [][3]uint32{{1, 1, 1}, {2, 0, 1}, {2, 3, 3}} // ids 3, 8, 15

// leafTiles is the tile set of leaves-gzip: 14 tile entries split into two
// leaf directories of seven (ids 0-11 and 15-19078479), so every tile is
// reached through a leaf. "big" at id 2 pushes the data of every content
// first used after it past the first 16 KiB.
var leafTiles = []tile{
	{0, 0, 0, "red"},                                        // id 0
	{1, 0, 0, "green"},                                      // id 1
	{1, 0, 1, "big"},                                        // id 2
	{1, 1, 0, "red"},                                        // id 4, dedup of id 0
	{2, 0, 0, "gray"}, {2, 1, 0, "gray"}, {2, 1, 1, "gray"}, // ids 5-7: run of 3
	{2, 0, 2, "blue"},                        // id 9
	{2, 0, 3, "yellow"}, {2, 1, 3, "yellow"}, // ids 10-11: run of 2
	{2, 3, 3, "green"},                                                         // id 15, dedup of id 1; first entry of leaf 2
	{2, 3, 0, "purple"},                                                        // id 20
	{3, 0, 0, "gray"}, {3, 0, 1, "gray"}, {3, 1, 1, "gray"}, {3, 1, 0, "gray"}, // ids 21-24
	{3, 2, 0, "gray"}, {3, 3, 0, "gray"}, {3, 3, 1, "gray"}, {3, 2, 1, "gray"}, // ids 25-28: run of 8, dedup of id 5
	{3, 3, 2, "orange"},      // id 30
	{3, 0, 5, "red"},         // id 40, dedup of id 0
	{3, 7, 0, "blue"},        // id 84, last z3 tile, dedup of id 9
	{12, 3423, 1763, "cyan"}, // id 19078479, the spec example
}

// leafAbsent are coordinates with no tile: in leaf 1's range (ids 3, 8, 13)
// and leaf 2's range (ids 29, 50, 83 and both neighbours of the spec
// example, 19078478 and 19078480).
var leafAbsent = [][3]uint32{{1, 1, 1}, {2, 0, 1}, {2, 2, 2}, {3, 2, 2}, {3, 2, 5}, {3, 7, 1},
	{12, 3422, 1763}, {12, 3423, 1762}}

var rootFeatures = []string{"root-only", "contiguous-offsets", "deduplicated-content", "noncontiguous-offsets", "run-length", "absent-tiles", "multi-zoom"}

func validSpecs() []spec {
	return []spec{
		{
			name:        "root-none",
			description: "Root directory only, internal compression none.",
			features:    rootFeatures,
			compression: pmtiles.CompressionNone,
			tiles:       rootTiles,
			absent:      rootAbsent,
		},
		{
			name:        "root-gzip",
			description: "Same tiles as root-none; root directory and metadata gzip-compressed (stored deflate blocks).",
			features:    append(append([]string{}, rootFeatures...), "internal-gzip"),
			compression: pmtiles.CompressionGzip,
			tiles:       rootTiles,
			absent:      rootAbsent,
		},
		{
			name: "leaves-gzip",
			description: "Root directory holds only two leaf entries; every tile is found through a gzip leaf directory. " +
				"z0-z3 plus the spec example 12/3423/1763 (tile id 19078479). A 27812-byte tile at id 2 puts later tile data past the first 16 KiB.",
			features: []string{"leaf-directories", "root-leaf-entries-only", "internal-gzip", "contiguous-offsets", "deduplicated-content",
				"noncontiguous-offsets", "run-length", "absent-tiles", "multi-zoom", "spec-example-tile", "data-beyond-16k"},
			compression: pmtiles.CompressionGzip,
			tiles:       leafTiles,
			absent:      leafAbsent,
			leafSize:    7,
		},
	}
}

// Generate builds the whole corpus in memory: manifest.json first, then
// archives sorted by path.
func Generate() ([]File, *Manifest, error) {
	m := &Manifest{Schema: ManifestSchema, Generator: Generator{"pmtiles-lab", Version}, Spec: specRef}
	var files []File
	for _, s := range validSpecs() {
		b := build(s)
		path := "valid/" + s.name + ".pmtiles"
		files = append(files, File{path, b.bytes})
		m.Archives = append(m.Archives, Archive{
			Name: s.name, File: path, Kind: "valid", SHA256: sum(b.bytes), Size: len(b.bytes),
			Description: s.description, Features: s.features,
			Header: &HeaderFacts{
				InternalCompression: b.header.InternalCompression.String(),
				TileCompression:     b.header.TileCompression.String(),
				TileType:            b.header.TileType.String(),
				Clustered:           b.header.Clustered == 1,
				MinZoom:             b.header.MinZoom, MaxZoom: b.header.MaxZoom,
			},
			Tiles: expectations(s, b),
		})
	}
	for _, mc := range malformedCases() {
		b := mc.build()
		path := mc.kind + "/" + mc.name + ".pmtiles"
		files = append(files, File{path, b})
		m.Archives = append(m.Archives, Archive{
			Name: mc.name, File: path, Kind: mc.kind, SHA256: sum(b), Size: len(b),
			Description: mc.description, ExpectedError: string(mc.code),
		})
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	mb, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, nil, err
	}
	files = append([]File{{"manifest.json", append(mb, '\n')}}, files...)
	return files, m, nil
}

// expectations derives the expected lookup for every listed coordinate from
// the builder's own layout (not from the reader under test).
func expectations(s spec, b built) []TileExpect {
	var out []TileExpect
	add := func(z uint8, x, y uint32, content string) {
		id, _ := pmtiles.ZxyToID(z, x, y)
		t := TileExpect{Z: z, X: x, Y: y, TileID: id, Status: "absent"}
		if content != "" {
			t.Status, t.Content = "present", content
			blob := contents[content]
			t.SHA256, t.Length = sum(blob), uint64(len(blob))
			off := b.header.TileDataOffset + b.offsets[content]
			t.ArchiveOffset = &off
		}
		if s.leafSize > 0 {
			t.LeafDirectory = leafFor(b, id)
		}
		out = append(out, t)
	}
	for _, t := range s.tiles {
		add(t.z, t.x, t.y, t.content)
	}
	for _, a := range s.absent {
		add(uint8(a[0]), a[1], a[2], "")
	}
	sort.Slice(out, func(i, j int) bool { return out[i].TileID < out[j].TileID })
	return out
}

// leafFor returns the absolute range of the leaf a lookup for id must read,
// taken from the builder's own root layout (not decoded back from bytes), or
// nil if the id precedes every leaf.
func leafFor(b built, id uint64) *LeafRef {
	var ref *LeafRef
	for _, e := range b.rootEntries {
		if e.RunLength != 0 {
			panic("leafFor: root directory has tile entries")
		}
		if e.TileID <= id {
			ref = &LeafRef{b.header.LeafOffset + e.Offset, e.Length}
		}
	}
	return ref
}

func sum(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}

// WriteDir writes files under dir. It refuses a non-empty directory unless it
// already holds a pmtiles-lab manifest and force is set.
func WriteDir(dir string, files []File, force bool) error {
	ents, err := os.ReadDir(dir)
	switch {
	case errors.Is(err, os.ErrNotExist):
	case err != nil:
		return err
	case len(ents) > 0:
		if !isLabDir(dir) {
			return fmt.Errorf("%s is not empty and has no pmtiles-lab manifest; refusing to write", dir)
		}
		if !force {
			return fmt.Errorf("%s already holds a generated corpus; pass --force to overwrite", dir)
		}
	}
	for _, f := range files {
		p := filepath.Join(dir, filepath.FromSlash(f.Path))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, f.Bytes, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func isLabDir(dir string) bool {
	b, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
	if err != nil {
		return false
	}
	var m struct{ Schema string }
	return json.Unmarshal(b, &m) == nil && m.Schema == ManifestSchema
}
