// Package fixtures generates the deterministic synthetic PMTiles corpus and
// its manifest. Output depends only on this package's source.
package fixtures

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/lansenou/pmtiles-conformance-lab/internal/pmtiles"
)

// Version is the generator version recorded in the manifest. Bump it whenever
// generated bytes change.
const Version = "0.1.0"

// Spec pin (docs/plan.md §2).
var specRef = SpecRef{
	Repository: "https://github.com/protomaps/PMTiles",
	Path:       "spec/v3/spec.md",
	Revision:   "8b8ddea4dbff1b0104cf2bebf2f7ff35c91b41d5",
	Version:    "3.6",
}

// ManifestSchema identifies the manifest format.
const ManifestSchema = "pmtiles-lab-manifest/1"

// File is one generated file.
type File struct {
	Path  string // slash-separated, relative to the output directory
	Bytes []byte
}

// rootTiles is the tile set shared by the root-only fixtures: contiguous
// offsets (0,1,2), a deduplicated tile (id 4 reuses id 0's bytes: a backward,
// noncontiguous offset), a run of three (ids 5-7), a z2 tile and absences.
var rootTiles = []tile{
	{0, 0, 0, "red"},
	{1, 0, 0, "green"},
	{1, 0, 1, "blue"},
	{1, 1, 0, "red"},                                        // id 4, dedup of id 0
	{2, 0, 0, "gray"}, {2, 1, 0, "gray"}, {2, 1, 1, "gray"}, // ids 5, 6, 7: one run
	{2, 3, 0, "yellow"}, // id 20
}

var rootAbsent = [][3]uint32{{1, 1, 1}, {2, 0, 1}, {2, 3, 3}} // ids 3, 8, 15

func validSpecs() []spec {
	return []spec{
		{
			name:        "root-none",
			description: "Root directory only, internal compression none.",
			features:    []string{"root-only", "contiguous-offsets", "deduplicated-content", "noncontiguous-offsets", "run-length", "absent-tiles", "multi-zoom"},
			compression: pmtiles.CompressionNone,
			tiles:       rootTiles,
			absent:      rootAbsent,
		},
	}
}

// Generate builds the whole corpus in memory: manifest.json first, then
// archives sorted by path.
func Generate() ([]File, *Manifest, error) {
	m := &Manifest{Schema: ManifestSchema, Generator: Generator{"pmtiles-lab", Version}, Spec: specRef}
	var files []File
	for _, s := range validSpecs() {
		b := build(s)
		path := "valid/" + s.name + ".pmtiles"
		files = append(files, File{path, b.bytes})
		m.Archives = append(m.Archives, Archive{
			Name: s.name, File: path, Kind: "valid", SHA256: sum(b.bytes), Size: len(b.bytes),
			Description: s.description, Features: s.features,
			Header: &HeaderFacts{
				InternalCompression: b.header.InternalCompression.String(),
				TileCompression:     b.header.TileCompression.String(),
				TileType:            b.header.TileType.String(),
				Clustered:           b.header.Clustered == 1,
				MinZoom:             b.header.MinZoom, MaxZoom: b.header.MaxZoom,
			},
			Tiles: expectations(s, b),
		})
	}
	for _, mc := range malformedCases() {
		b := mc.build()
		path := mc.kind + "/" + mc.name + ".pmtiles"
		files = append(files, File{path, b})
		m.Archives = append(m.Archives, Archive{
			Name: mc.name, File: path, Kind: mc.kind, SHA256: sum(b), Size: len(b),
			Description: mc.description, ExpectedError: string(mc.code),
		})
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	mb, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, nil, err
	}
	files = append([]File{{"manifest.json", append(mb, '\n')}}, files...)
	return files, m, nil
}

// expectations derives the expected lookup for every listed coordinate from
// the builder's own layout (not from the reader under test).
func expectations(s spec, b built) []TileExpect {
	var out []TileExpect
	add := func(z uint8, x, y uint32, content string) {
		id, _ := pmtiles.ZxyToID(z, x, y)
		t := TileExpect{Z: z, X: x, Y: y, TileID: id, Status: "absent"}
		if content != "" {
			t.Status, t.Content = "present", content
			blob := contents[content]
			t.SHA256, t.Length = sum(blob), uint64(len(blob))
			off := b.header.TileDataOffset + uint64(bytes.Index(b.data, blob))
			t.ArchiveOffset = &off
		}
		if s.leafSize > 0 {
			t.LeafDirectory = leafFor(b, id)
		}
		out = append(out, t)
	}
	for _, t := range s.tiles {
		add(t.z, t.x, t.y, t.content)
	}
	for _, a := range s.absent {
		add(uint8(a[0]), a[1], a[2], "")
	}
	sort.Slice(out, func(i, j int) bool { return out[i].TileID < out[j].TileID })
	return out
}

// leafFor returns the absolute range of the leaf a lookup for id must read,
// or nil if the id precedes every leaf.
func leafFor(b built, id uint64) *LeafRef {
	root, err := pmtiles.Decompress(b.header.InternalCompression, b.bytes[b.header.RootOffset:b.header.RootOffset+b.header.RootLength], 1<<20)
	if err != nil {
		panic(err)
	}
	entries, err := pmtiles.DecodeDirectory(root, 1<<16)
	if err != nil {
		panic(err)
	}
	var ref *LeafRef
	for _, e := range entries {
		if e.TileID <= id {
			ref = &LeafRef{b.header.LeafOffset + e.Offset, e.Length}
		}
	}
	return ref
}

func sum(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}

// WriteDir writes files under dir. It refuses a non-empty directory unless it
// already holds a pmtiles-lab manifest and force is set.
func WriteDir(dir string, files []File, force bool) error {
	ents, err := os.ReadDir(dir)
	switch {
	case errors.Is(err, os.ErrNotExist):
	case err != nil:
		return err
	case len(ents) > 0:
		if !isLabDir(dir) {
			return fmt.Errorf("%s is not empty and has no pmtiles-lab manifest; refusing to write", dir)
		}
		if !force {
			return fmt.Errorf("%s already holds a generated corpus; pass --force to overwrite", dir)
		}
	}
	for _, f := range files {
		p := filepath.Join(dir, filepath.FromSlash(f.Path))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, f.Bytes, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func isLabDir(dir string) bool {
	b, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
	if err != nil {
		return false
	}
	var m struct{ Schema string }
	return json.Unmarshal(b, &m) == nil && m.Schema == ManifestSchema
}
